epochs: 100
batch_size: 512
patience: 20
milestone_step: 10
gamma: 0.5
lr: 0.001
dataset: '2016.10b'

num_classes: 10
sig_len: 128
extend_channel: 36
latent_dim: 512
num_heads: 2
conv_chan_list: [36, 64, 128, 256]

monitor: 'acc'
test_batch_size: 64